workspace(name = "minions")

git_repository(
    name = "io_bazel_rules_go",
    remote = "https://github.com/bazelbuild/rules_go.git",
    tag = "0.12.0",
)

load(
    "@io_bazel_rules_go//go:def.bzl",
    "go_register_toolchains",
    "go_repository",
    "go_rules_dependencies",
)

git_repository(
    name = "bazel_gazelle",
    remote = "https://github.com/bazelbuild/bazel-gazelle.git",
    tag = "0.12.0",
)

# Buildifier
http_archive(
    name = "com_github_bazelbuild_buildtools",
    strip_prefix = "buildtools-4fe6acf537e980ff6878a51e5894605be221224c",
    url = "https://github.com/bazelbuild/buildtools/archive/4fe6acf537e980ff6878a51e5894605be221224c.zip",
)

load("@io_bazel_rules_go//go:def.bzl", "go_register_toolchains", "go_rules_dependencies")
load("@com_github_bazelbuild_buildtools//buildifier:deps.bzl", "buildifier_dependencies")

buildifier_dependencies()

git_repository(
    name = "io_bazel_rules_docker",
    remote = "https://github.com/bazelbuild/rules_docker.git",
    tag = "v0.4.0",
)

git_repository(
    name = "in_gopkg_resty_v1",
    remote = "https://github.com/go-resty/resty",
    tag = "v1.5",
)

git_repository(
    name = "org_pubref_rules_protobuf",
    remote = "https://github.com/pubref/rules_protobuf.git",
    tag = "v0.8.1",
)

go_repository(
    name = "com_github_stretchr_testify",
    importpath = "github.com/stretchr/testify",
    tag = "v1.2.1",
)

go_repository(
    name = "com_github_necomeshi_rpmlib",
    commit = "213163e05c8656cac508c4b1352179d6f2e73202",
    importpath = "github.com/necomeshi/rpmlib",
    remote = "https://github.com/paradoxengine/rpmlib",
    vcs = "git",
)

new_git_repository(
    name = "com_github_google_uuid",
    build_file_content = """
load("@io_bazel_rules_go//go:def.bzl", "go_prefix")
load("@io_bazel_rules_go//go:def.bzl", "go_library")
go_prefix("github.com/google/uuid")
go_library(
    name = "go_default_library",
    srcs = glob(["*.go"], exclude=["*_test.go"]),
    deps = [
    ],
    visibility = ["//visibility:public"],
)
    """,
    remote = "https://github.com/google/uuid",
    tag = "0.2",
)

# See this URL for a list of the things this imports:
# https://github.com/bazelbuild/rules_go/blob/master/go/workspace.rst#go_rules_dependencies
go_rules_dependencies()

go_register_toolchains()

load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies")

gazelle_dependencies()

load(
    "@io_bazel_rules_docker//go:image.bzl",
    docker_go_image_repos = "repositories",
)

docker_go_image_repos()
